ccflags-y += -Wno-strict-aliasing -Wno-unused-label -Wno-pointer-sign -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function

obj-y += uip.o
obj-y += uip_arp.o
obj-y += uiplib.o
obj-y += timer.o
obj-y += uip-neighbor.o
obj-y += dhcpd.o
obj-y += main.o
obj-y += clock-arch.o